#!/usr/bin/env bash

set -euo pipefail

dir=$PWD

[[ "${1-}" != "" ]] && dir=${1}

if [[ "${IMG_VERSION-}" != "" ]]; then
    echo "${IMG_VERSION}"
else
    if [[ "${OFFICIAL_BUILD-}" != "" ]]; then
        cat "${dir}/VERSION"
    else
        echo "0.0.0+$(git rev-parse --short HEAD)"
    fi
fi
